apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "web-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "web-api.selectorLabels" . | nindent 4 }}
