apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-frontend.fullname" . }}
  labels:
    {{- include "react-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: react
  selector:
    {{- include "react-frontend.selectorLabels" . | nindent 4 }}
